# Generated SDK-only workspace. Edit the private source repository.
[workspace]
resolver = "1"
members = ["sdk", "sdk/macros", "sdk/event-publication-sqlx", "contracts/foundation", "contracts/event-dispatch", "contracts/runtime"]
default-members = ["sdk"]

[workspace.dependencies]
async-stream = "0.3.6"
async-trait = "0.1.89"
axum = { "version" = "0.8.4", "features" = ["ws", "multipart"] }
base64 = "0.22"
bytes = { "version" = "1", "features" = ["serde"] }
chrono = { "version" = "0.4.31", "features" = ["serde"] }
chrono-tz = { "version" = "0.10", "features" = ["serde"] }
cron = { "version" = "0.15.0" }
futures = "0.3.29"
futures-util = "0.3.29"
http = "1"
httpdate = "1"
inventory = "0.3"
jsonschema = { "version" = "0.33", "default-features" = false }
kish-lingshu-event-dispatch-contract = { "path" = "contracts/event-dispatch" }
kish-lingshu-foundation-contract = { "path" = "contracts/foundation" }
kish-lingshu-runtime-contract = { "path" = "contracts/runtime" }
kish-lingshu-sdk = { "path" = "sdk", "default-features" = false }
percent-encoding = "2.3"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
rand = "0.8"
reqwest = { "version" = "0.12.20", "default-features" = false, "features" = ["stream", "json", "rustls-tls-webpki-roots-no-provider", "rustls-tls-native-roots-no-provider", "cookies", "multipart"] }
rustls = { "version" = "0.23", "default-features" = false, "features" = ["ring", "logging", "std", "tls12"] }
schemars = { "version" = "1.2.0", "features" = ["chrono04", "uuid1"] }
serde = "1.0.190"
serde_json = { "version" = "1.0.107", "features" = ["preserve_order"] }
sha2 = "0.10"
sqlx = { "version" = "0.8", "features" = ["runtime-tokio", "tls-rustls", "any", "postgres", "mysql", "sqlite"] }
syn = { "version" = "2", "features" = ["full"] }
tempfile = "3.27"
thiserror = "1.0.50"
tokio = { "version" = "1.49.0", "features" = ["full", "macros", "rt-multi-thread", "signal"] }
url = { "version" = "2.5.0" }
uuid = { "version" = "1.17.0", "features" = ["v4", "v7"] }
